ruby '2.2.2'
source 'https://rubygems.org'
gem 'dotenv-rails'
gem 'jquery-rails'
gem 'pg'
gem 'pry-nav'
gem 'rails', '4.2.4.rc1'
gem 'rom', '0.9.0.rc1'
gem 'rom-rails', '0.5.0.rc1'
gem 'rom-sql', '0.6.0.rc1'
gem 'sass-rails'
gem 'slim-rails'
gem 'uglifier'
